version: 2
jobs:
  build-publish-trigger:
    machine:
      image: buntu-2204:2022.10.2
    steps:
      - checkout
      - run:
          name: Build image, test it, tag it, publish it
          command: |
            # DOCKER_USER, DOCKER_PASS are in ci context
            echo "${DOCKER_PASS}" | docker login --username "${DOCKER_USER}" --password-stdin
            ./build_test_publish.sh
            docker logout

workflows:
  version: 2
  build-publish-trigger:
    jobs:
      - build-publish-trigger:
          context: cyberdojo-context
          filters:
            branches:
              only:
                  - master
